// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgGlTz-RkM5GzRYGbOrS5UJrChZ0UeKC8',
    appId: '1:295618886102:android:2064d45045836b2b420c77',
    messagingSenderId: '295618886102',
    projectId: 'pddh-sat-edd5e',
    storageBucket: 'pddh-sat-edd5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-ah1T2jv-RCy8yhLkwZXbJN2PjHDAVXA',
    appId: '1:295618886102:ios:8d6f72aed7b07ce9420c77',
    messagingSenderId: '295618886102',
    projectId: 'pddh-sat-edd5e',
    storageBucket: 'pddh-sat-edd5e.appspot.com',
    iosClientId: '295618886102-ipa6kg1pu386d3bh8e75pfau2bkknjil.apps.googleusercontent.com',
    iosBundleId: 'com.thenextservices.sat',
  );
}
